version: "3.7"

services:
  nucifera-db:
    image: postgres:13
    container_name: nucifera-db
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9221
      - POSTGRES_DB=nuciferaDB
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/tables_init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - nucifera
  
  flask-app:
    build:
      context: ./backendFlask
      dockerfile: ./Dockerfile
    ports:
      - "5002:5000"
    restart: on-failure
    networks:
      - nucifera

volumes:
  postgres-data:

networks:
  nucifera:
    name: nucifera